name: Notify Discord on Release

on:
  release:
    types: 
      - published

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
     - name: Discord notification
       env:
          DISCORD_WEBHOOK: ${{secrets.DISCORD_TOKEN}}
       uses: Ilshidur/action-discord@master
       with:
          args: "### A new release for Markus Kart is now available (${{github.event.release.tag_name}})🎉\n https://raw.githubusercontent.com/Npulseee/Markus-Kart/main/repository-open-graph-template.png"
