name: Notify Discord on Release

on:
  release:
    types: 
      - published
      - updated

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
     - name: Discord notification
       env:
          DISCORD_WEBHOOK: ${{secrets.DISCORD_TOKEN}}
       uses: Ilshidur/action-discord@master
       with:
       #${{github.event.release.body}}
          args: "## A new release for Markus Kart is now available (${{github.event.release.tag_name}}) 🎉\n ${{github.event.release.body}} \n ![Release Image](https://raw.githubusercontent.com/Npulseee/Markus-Kart/main/repository-open-graph-template.png)"
