
name: Create Release Zip

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Zip Folder
        run: zip -r release.zip .

      - name: Upload Zip
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release.zip
