name: Notify Discord on Release

on: workflow_dispatch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
     - name: Discord notification
       env:
          DISCORD_WEBHOOK: ${{secrets.DISCORD_TOKEN}}
       uses: Ilshidur/action-discord@master
       with:
          args: "[## A new release for Markus Kart is now available (v0.2.5) 🎉](https://raw.githubusercontent.com/Npulseee/Markus-Kart/main/repository-open-graph-template.png)"
